"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
require("./App.css");
require("./style.css");
var about = function () {
    return (React.createElement("div", { className: "page" },
        React.createElement("div", { className: "" },
            React.createElement("div", { className: "info" },
                React.createElement("div", { className: "info__item" },
                    React.createElement("div", { className: "photo" },
                        React.createElement("div", { className: "photo__item" },
                            React.createElement("img", { src: 'https://imgur.com/nFgnGMP.png' }))),
                    React.createElement("div", { className: "profile" },
                        React.createElement("div", { className: "profile__title title1" }, "Profile"),
                        React.createElement("div", { className: "profile__text" }, "I`m 21 years old, living in Chernivtsi, Ukraine. For whole my life i was always interested in Computer Science and tried to understand how to use this passion in future. When i had to decide which profession would accomplish earning money and doing what i love most i found out that Department of Computer Science in Institute of Physical, Technical and Computer Sciences would be the best decision. I always trying to learn new information from everywhere: from university, from different internet sources etc. I really think that your company is the best variant for me, because it`s a great experience, new connections and my possibility of career development. Moreover, I would like to work in team because of my sociable skills and leader qualities. I can perceive a new information and use it as quick as it possible.")),
                    React.createElement("div", { className: "contact" },
                        React.createElement("div", { className: "contact__title title1" }, "Contact"),
                        React.createElement("div", { className: "contact__phone" }, "+380956446876"),
                        React.createElement("div", { className: "contact__address" }, "Chernivtsi, Heroiv Maidanu st., 93 "),
                        React.createElement("div", { className: "contact__index" }, "58013"),
                        React.createElement("a", { href: "mailto:korolenkovitya92@gmail.com", className: "contact__email" }, "korolenkovitya92@gmail.com"),
                        React.createElement("a", { href: "https://www.instagram.com/viktor__braus/", className: "contact__insta" }, "Instagram"))),
                React.createElement("div", { className: "info__item" },
                    React.createElement("div", { className: "education" },
                        React.createElement("div", { className: "education__title title1" }, "Education"),
                        React.createElement("div", { className: "education__uni" }, "CHERNIVTSI NATIONAL UNIVERSITY"),
                        React.createElement("div", { className: "education__spec" }, "2017 - 2021 | Computer Science "),
                        React.createElement("div", { className: "education__school" }, "Chernivtsi gymnasia \u21167 \u2022 2006-2017 "),
                        React.createElement("div", { className: "education__type" }, "Secondary Education")),
                    React.createElement("div", { className: "experience" },
                        React.createElement("div", { className: "experience__title title1" }, "Experience"),
                        React.createElement("div", { className: "experience__work" },
                            "\"Latte\" Cafe, jun 2018 - aug 2018 ",
                            React.createElement("br", null),
                            "Barista")),
                    React.createElement("div", { className: "hobbies" },
                        React.createElement("div", { className: "hobbies__title title1" }, "Hobbies"),
                        React.createElement("ul", { className: "hobbies__list" },
                            React.createElement("li", null, "Singer"),
                            React.createElement("li", null, "Drawing"),
                            React.createElement("li", null, "Recording and publishing videos"),
                            React.createElement("li", null, "Blogging"))),
                    React.createElement("div", { className: "skills" },
                        React.createElement("div", { className: "skills__title title1" }, "Skills"),
                        React.createElement("div", { className: "skills__body" },
                            React.createElement("div", { className: "skills__name" }, "HTML"),
                            React.createElement("div", { className: "skills__point" },
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }))),
                        React.createElement("div", { className: "skills__body" },
                            React.createElement("div", { className: "skills__name" }, "CSS"),
                            React.createElement("div", { className: "skills__point" },
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }))),
                        React.createElement("div", { className: "skills__body" },
                            React.createElement("div", { className: "skills__name" }, "Photoshop"),
                            React.createElement("div", { className: "skills__point" },
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }))),
                        React.createElement("div", { className: "skills__body" },
                            React.createElement("div", { className: "skills__name" }, "Git"),
                            React.createElement("div", { className: "skills__point" },
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }))),
                        React.createElement("div", { className: "skills__body" },
                            React.createElement("div", { className: "skills__name" }, "C#"),
                            React.createElement("div", { className: "skills__point" },
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }))),
                        React.createElement("div", { className: "skills__body" },
                            React.createElement("div", { className: "skills__name" }, "JavaScript"),
                            React.createElement("div", { className: "skills__point" },
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }))),
                        React.createElement("div", { className: "skills__body" },
                            React.createElement("div", { className: "skills__name" }, "English"),
                            React.createElement("div", { className: "skills__point" },
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "empty" }))),
                        React.createElement("div", { className: "skills__body" },
                            React.createElement("div", { className: "skills__name" }, "Postman"),
                            React.createElement("div", { className: "skills__point" },
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }))),
                        React.createElement("div", { className: "skills__body" },
                            React.createElement("div", { className: "skills__name" }, "Sql, MySql"),
                            React.createElement("div", { className: "skills__point" },
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }))),
                        React.createElement("div", { className: "skills__body" },
                            React.createElement("div", { className: "skills__name" }, "PostgreSql"),
                            React.createElement("div", { className: "skills__point" },
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }))),
                        React.createElement("div", { className: "skills__body" },
                            React.createElement("div", { className: "skills__name" }, "Python"),
                            React.createElement("div", { className: "skills__point" },
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "circle" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" }),
                                React.createElement("div", { className: "empty" })))))))));
};
exports.default = about;
//# sourceMappingURL=About.js.map